### ISSUE TITLE
Cancellation of promises

### ISSUE THREAD

**Issue by ghost** [async-interop/promise#38]
Are there any plans to specify an interoperable way to cancel promises?

A unified means of cancellation would be very useful within combinators (await first, await all, etc.) that combine or chain multiple promises together. Another interesting use case would be to cancel promises using timers without having to implement a timeout in every promise class (could be implemented using a Timeout promise that decorates another (cancellable) promise with the timeout feature).

Cancellation support could be added by introducing a new interface:
```php
interface CancellablePromise extends Promise
{
    /**
     * Cancel the promise with the given reason if it is not resolved yet.
     *
     * @param \Exception|\Throwable $reason
     **/
    public function cancel($reason);
}
```
This would allow promise implementations to choose if they want to offer cancellation support without enforcing it on everybody. Cancelling a resolved (succeeded or failed) promise should not be treated as an error because there is no unified way to determine the status of a promise.

**Comment by kelunik** [comment]
The specification does currently only cover consumption of promises, no resolution / canceling. Resolution and consumption should be strictly separated IMO and canceling according to your suggestion seems to be some kind of resolution?

In general, there can be multiple `when()` handlers. What if a single one cancels the promise, but the others are still interested in the result? If we want something for combinators, I'd be something to unregister your `when` callback again I guess. The only benefit is allowing resources bound to closures being freed immediately instead of when the promise resolves. It doesn't save function calls, as it doesn't matter whether we just `return;` in the callback or call `unregister()` or something like that.

**Comment by ghost** [comment]
I think you are right about memory usage in combinators, cancellation of promises would not be helpful in this case. Cancellation could be beneficial when cancelling HTTP requests, DB queries or file processing though. Having multiple `when()` handlers is definitely a difficult situation...

**Comment by joshdifabio** [comment]
This is related to #10.

I tend to agree with @kelunik; I'm uncomfortable with a generic `Promise::cancel()` method which performs resolution, because unrelated consumers might still be interested in the real result of the promise.

In theory, being able to say that you _no longer care_ about the result of a promise has its uses, particularly when implementing combinators, but I think that in #10 we came to the conclusion that that alone wasn't important enough for us to include cancellation in the spec. Although I personally see the benefit of _don't care_ cancellation, I think that the arguments not to include it in this spec were reasonable.

**Comment by ghost** [comment]
Sorry i brought this up again. I somehow missed out on #10 completely.
